# http.host: "0.0.0.0"

path.config: /usr/share/logstash/pipeline
path.logs: /var/log/logstash

pipeline.ordered: false
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["https://es01:9200"]

xpack.monitoring.elasticsearch.username: "elastic" # Or create a dedicated logstash_internal user
xpack.monitoring.elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
xpack.monitoring.elasticsearch.ssl.certificate_authority: "/usr/share/logstash/config/certs/ca/ca.crt"
xpack.monitoring.elasticsearch.ssl.verification_mode: "certificate"
